FROM rust:1.68 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release --bin worker

FROM debian:buster-slim
COPY --from=builder /usr/src/app/target/release/worker /usr/local/bin/worker
CMD ["worker"]