FROM rust:1.68 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release

FROM debian:buster-slim
COPY --from=builder /usr/src/app/target/release/weapon_optimizer /usr/local/bin/weapon_optimizer
CMD ["weapon_optimizer"]