use serde::{Deserialize, Serialize};
use crate::modules::*;
use strum_macros::{EnumString, Display};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumString, Display)]
pub enum WeaponType {
    AssaultRifle, BeamRifle, HandCannon, Handgun, Launcher, MachineGun, ScoutRifle, Shotgun,
    SniperRifle, SubmachineGun, TacticalRifle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumString, Display)]
pub enum BulletType {
    GeneralRounds,
    SpecialRounds,
    ImpactRounds,
    HighPowerRounds
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Roll {
    pub roll_type: RollType,
    pub value: f64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum RollType {
    Atk, ElementAtk, WeakPointDamage, Crit, CritDamage, RoundsPerMagazine, ColossusDamage,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Module {
    pub name: String,
    pub module_type: ModuleType,
    pub effects: Vec<ModuleEffect>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModuleBonusType {
    Atk, WeakPointDamage, Crit, CritDamage, RoundsPerMagazine, ReloadTime, FireRate,
    EleEnhancement, EleMult, FiringFiesta, ShellCapacity
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ModuleEffect {
    pub effect_type: ModuleBonusType,
    pub value: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModuleType {
    None,
    Atk,
    SpecialMod,
    FireRate,
    EleEnhancement,
    WeakPointStrike,
    Crit,
    CritDamage,
    RoundsPerMagazine,
    ReloadTime,
    Recoil,
    Accuracy,
    Gunbarrel,
    FiringFiesta,
}

impl From<usize> for ModuleType {
    fn from(value: usize) -> Self {
        // Implement the conversion from usize to ModuleType
        // You may need to adjust this based on your exact ModuleType enum
        match value {
            0 => ModuleType::None,
            1 => ModuleType::Atk,
            2 => ModuleType::SpecialMod,
            3 => ModuleType::FireRate,
            4 => ModuleType::EleEnhancement,
            5 => ModuleType::WeakPointStrike,
            6 => ModuleType::Crit,
            7 => ModuleType::CritDamage,
            8 => ModuleType::RoundsPerMagazine,
            9 => ModuleType::ReloadTime,
            10 => ModuleType::Recoil,
            11 => ModuleType::Accuracy,
            12 => ModuleType::Gunbarrel,
            13 => ModuleType::FiringFiesta,
            _ => panic!("Invalid ModuleType value"),
        }
    }
}

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, EnumString, Display)]
pub enum Weapon {
    // AssaultRifle
    CaligosHorn,
    DivinePunishment,
    EternalWillpower,
    FallenHope,
    MagnusAA,
    OminousHound,
    PhantomPain,
    // BeamRifle
    // HandCannon
    AssassinsEdge,
    BurningHound,
    ExplorersPath,
    ImmediateExecution,
    NazeistrasDevotion,
    Perferator,
    // Handgun
    MillenniumFrost,
    HungryHound,
    NewBeginning,
    RedWolf,
    TheLastDagger,
    RoseOfAisha,
    TheFinalMaster,
    // Launcher
    DeathRoar,
    GuardianR4,
    LightspeedBarrel,
    RestoredRelic,
    SigvoresProof,
    TamedBeast,
    VestigialOrgan,
    // MachineGun
    AlbionCavalryGun,
    Cygnus,
    EnduringLegacy,
    LionOfBlueMane,
    RascalV51,
    Tamer,
    UnfinishedStudy,
    // ScoutRifle
    BlueBeetle,
    HerosScar,
    NightmareHound,
    SillyWeeper,
    SonicCoOp,
    TheAgeOfInnovation,
    WaveOfLight,
    // Shotgun
    Executor,
    Fireworks,
    Gangster,
    InABlink,
    Smithereens,
    Subconsciousness,
    TheLastKnight,
    // SniperRifle
    AfterglowSword,
    Belief,
    DifferentDream,
    ForrestGaze,
    PiercingLight,
    RecipientUnknown,
    SupermoonZ15,
    // SubmachineGun
    Albinism,
    AlterEgo,
    BlueBloodBloomer,
    DevilsCall,
    Firefly,
    Python,
    Thundercage,
    // TacticalRifle
    Detachment,
    GregsReversedFate,
    SecretGarden,
    RedEye,
    TheUnwelcomed,
    Viper,
    YoungNoblesAmbition,
}

impl Weapon {
    pub fn all() -> &'static [Weapon] {
        &[
            // AssaultRifle
            // AssaultRifle
            Weapon::CaligosHorn,
            Weapon::DivinePunishment,
            Weapon::EternalWillpower,
            Weapon::FallenHope,
            Weapon::MagnusAA,
            Weapon::OminousHound,
            Weapon::PhantomPain,
            // BeamRifle
            // HandCannon
            Weapon::AssassinsEdge,
            Weapon::BurningHound,
            Weapon::ExplorersPath,
            Weapon::ImmediateExecution,
            Weapon::NazeistrasDevotion,
            Weapon::Perferator,
            // Handgun
            Weapon::MillenniumFrost,
            Weapon::HungryHound,
            Weapon::NewBeginning,
            Weapon::RedWolf,
            Weapon::TheLastDagger,
            Weapon::RoseOfAisha,
            Weapon::TheFinalMaster,
            // Launcher
            Weapon::DeathRoar,
            Weapon::GuardianR4,
            Weapon::LightspeedBarrel,
            Weapon::RestoredRelic,
            Weapon::SigvoresProof,
            Weapon::TamedBeast,
            Weapon::VestigialOrgan,
            // MachineGun
            Weapon::AlbionCavalryGun,
            Weapon::Cygnus,
            Weapon::EnduringLegacy,
            Weapon::LionOfBlueMane,
            Weapon::RascalV51,
            Weapon::Tamer,
            Weapon::UnfinishedStudy,
            // ScoutRifle
            Weapon::BlueBeetle,
            Weapon::HerosScar,
            Weapon::NightmareHound,
            Weapon::SillyWeeper,
            Weapon::SonicCoOp,
            Weapon::TheAgeOfInnovation,
            Weapon::WaveOfLight,
            // Shotgun
            Weapon::Executor,
            Weapon::Fireworks,
            Weapon::Gangster,
            Weapon::InABlink,
            Weapon::Smithereens,
            Weapon::Subconsciousness,
            Weapon::TheLastKnight,
            // SniperRifle
            Weapon::AfterglowSword,
            Weapon::Belief,
            Weapon::DifferentDream,
            Weapon::ForrestGaze,
            Weapon::PiercingLight,
            Weapon::RecipientUnknown,
            Weapon::SupermoonZ15,
            // SubmachineGun
            Weapon::Albinism,
            Weapon::AlterEgo,
            Weapon::BlueBloodBloomer,
            Weapon::DevilsCall,
            Weapon::Firefly,
            Weapon::Python,
            Weapon::Thundercage,
            // TacticalRifle
            Weapon::Detachment,
            Weapon::GregsReversedFate,
            Weapon::SecretGarden,
            Weapon::RedEye,
            Weapon::TheUnwelcomed,
            Weapon::Viper,
            Weapon::YoungNoblesAmbition,
        ]
    }
}

pub fn get_available_modules(bullet_type: BulletType, weapon_type: WeaponType) -> Vec<Module> {
    match bullet_type {
        BulletType::GeneralRounds => general_rounds_modules::get_modules(),
        BulletType::SpecialRounds => special_rounds_modules::get_modules(),
        BulletType::ImpactRounds => impact_rounds_modules::get_modules(),
        BulletType::HighPowerRounds => match weapon_type {
            WeaponType::SniperRifle => sniper_modules::get_modules(),
            WeaponType::Shotgun => shotgun_modules::get_modules(),
            WeaponType::Launcher => launcher_modules::get_modules(),
            _ => panic!("Invalid WeaponType with HighPowerRounds")
        }
    }
}

pub fn get_available_rolls(weapon_type: WeaponType) -> Vec<Roll> {
    match weapon_type {
        WeaponType::Handgun => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 1232.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.133 },
            Roll { roll_type: RollType::CritDamage, value: 0.368 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 2465.0 },
        ],
        WeaponType::HandCannon => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 5838.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.114 },
            Roll { roll_type: RollType::CritDamage, value: 0.215 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 11676.0 },
        ],
        WeaponType::Shotgun => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 1806.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.098 },
            Roll { roll_type: RollType::CritDamage, value: 0.111 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 3612.0 },
        ],
        WeaponType::SubmachineGun => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 1226.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.133 },
            Roll { roll_type: RollType::CritDamage, value: 0.368 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 2453.0 },
        ],
        WeaponType::MachineGun => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 1702.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.143 },
            Roll { roll_type: RollType::CritDamage, value: 0.411 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 3404.0 },
        ],
        WeaponType::AssaultRifle => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 1679.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.152 },
            Roll { roll_type: RollType::CritDamage, value: 0.449 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 3357.0 },
        ],
        WeaponType::TacticalRifle => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 1731.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.122 },
            Roll { roll_type: RollType::CritDamage, value: 0.247 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 3462.0 },
        ],
        WeaponType::ScoutRifle => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 4747.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.133 },
            Roll { roll_type: RollType::CritDamage, value: 0.327 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 9494.0 },
        ],
        WeaponType::SniperRifle => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 15196.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.108 },
            Roll { roll_type: RollType::CritDamage, value: 0.184 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 30393.0 },
        ],
        WeaponType::Launcher => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 14828.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.108 },
            Roll { roll_type: RollType::CritDamage, value: 0.184 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 29654.0 },
        ],
        WeaponType::BeamRifle => vec![
            Roll { roll_type: RollType::Atk, value: 0.122 },
            Roll { roll_type: RollType::ElementAtk, value: 1986.0 },
            Roll { roll_type: RollType::WeakPointDamage, value: 0.12 },
            Roll { roll_type: RollType::Crit, value: 0.133 },
            Roll { roll_type: RollType::CritDamage, value: 0.368 },
            Roll { roll_type: RollType::RoundsPerMagazine, value: 0.12 },
            Roll { roll_type: RollType::ColossusDamage, value: 3972.0 },
        ]
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct WeaponBaseStats {
    pub ele_enhancement: f64,
    pub flat_ele_atk: f64,
    pub colossus_atk: f64,
    pub ele_multiplier: f64,
    pub firing_fiesta: f64,
    pub weapon_type: WeaponType,
    pub bullet_type: BulletType,
    pub base_atk: f64,
    pub fire_rate: f64,
    pub magazine_capacity: f64,
    pub reload_time: f64,
    pub crit_chance: f64,
    pub crit_damage: f64,
    pub weak_point_damage: f64,
    pub bullets_per_shot: f64,
}

impl WeaponBaseStats {
    pub fn get(name: Weapon) -> Self {
        match name {
            Weapon::Thundercage => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11055.0,
                fire_rate: 666.0,
                magazine_capacity: 26.0,
                reload_time: 1.4,
                crit_chance: 0.20,
                crit_damage: 2.0,
                weak_point_damage: 1.2,
                bullets_per_shot: 1.0,
            },
            Weapon::FallenHope => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 12813.0,
                fire_rate: 600.0,
                magazine_capacity: 35.0,
                reload_time: 1.7,
                crit_chance: 0.12,
                crit_damage: 1.7,
                weak_point_damage: 1.2,
                bullets_per_shot: 1.0,
            },
            Weapon::Perferator => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 67092.0,
                fire_rate: 100.0,
                magazine_capacity: 6.0,
                reload_time: 1.6,
                crit_chance: 0.20,
                crit_damage: 2.0,
                weak_point_damage: 2.25,
                bullets_per_shot: 1.0,
            },
            Weapon::AssassinsEdge => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 40788.0,
                fire_rate: 120.0,
                magazine_capacity: 9.0,
                reload_time: 1.4,
                crit_chance: 0.40,
                crit_damage: 2.0,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::ImmediateExecution => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 36920.0,
                fire_rate: 171.0,
                magazine_capacity: 12.0,
                reload_time: 1.7,
                crit_chance: 0.32,
                crit_damage: 1.5,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::ExplorersPath => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 55281.0,
                fire_rate: 109.0,
                magazine_capacity: 9.0,
                reload_time: 1.4,
                crit_chance: 0.27,
                crit_damage: 1.3,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::NazeistrasDevotion => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 38461.0,
                fire_rate: 150.0,
                magazine_capacity: 8.0,
                reload_time: 1.5,
                crit_chance: 0.45,
                crit_damage: 2.25,
                weak_point_damage: 1.7,
                bullets_per_shot: 1.0,
            },
            Weapon::BurningHound => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 41726.0,
                fire_rate: 139.0,
                magazine_capacity: 12.0,
                reload_time: 1.75,
                crit_chance: 0.32,
                crit_damage: 1.5,
                weak_point_damage: 1.7,
                bullets_per_shot: 1.0,
            },
            Weapon::Tamer => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 17631.0,
                fire_rate: 625.0,
                magazine_capacity: 100.0,
                reload_time: 2.6,
                crit_chance: 0.10,
                crit_damage: 1.6,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::EternalWillpower => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 21370.0,
                fire_rate: 500.0,
                magazine_capacity: 25.0,
                reload_time: 1.9,
                crit_chance: 0.20,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::PiercingLight => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 193437.0,
                fire_rate: 48.0,
                magazine_capacity: 6.0,
                reload_time: 2.6,
                crit_chance: 0.40,
                crit_damage: 1.2,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::AfterglowSword => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 114206.0,
                fire_rate: 66.0,
                magazine_capacity: 6.0,
                reload_time: 2.5,
                crit_chance: 0.50,
                crit_damage: 2.0,
                weak_point_damage: 1.8,
                bullets_per_shot: 1.0,
            },
            Weapon::Viper => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 10359.0,
                fire_rate: 512.0,
                magazine_capacity: 50.0,
                reload_time: 1.75,
                crit_chance: 0.30,
                crit_damage: 1.85,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::YoungNoblesAmbition => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 13141.0,
                fire_rate: 455.0,
                magazine_capacity: 51.0,
                reload_time: 1.68,
                crit_chance: 0.35,
                crit_damage: 1.3,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::SecretGarden => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 10534.0,
                fire_rate: 480.0,
                magazine_capacity: 48.0,
                reload_time: 1.60,
                crit_chance: 0.50,
                crit_damage: 2.25,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::Detachment => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 17102.0,
                fire_rate: 360.0,
                magazine_capacity: 42.0,
                reload_time: 1.55,
                crit_chance: 0.30,
                crit_damage: 1.2,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::TheUnwelcomed => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 18108.0,
                fire_rate: 299.0,
                magazine_capacity: 36.0,
                reload_time: 1.54,
                crit_chance: 0.40,
                crit_damage: 1.5,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::EnduringLegacy => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 13155.0,
                fire_rate: 571.0,
                magazine_capacity: 115.0,
                reload_time: 2.70,
                crit_chance: 0.20,
                crit_damage: 1.7,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::GregsReversedFate => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 15614.0,
                fire_rate: 342.0,
                magazine_capacity: 30.0,
                reload_time: 1.4,
                crit_chance: 0.20,
                crit_damage: 2.0,
                weak_point_damage: 2.0,
                bullets_per_shot: 2.4,
            },
            Weapon::Python => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 9842.0,
                fire_rate: 923.0,
                magazine_capacity: 30.0,
                reload_time: 1.50,
                crit_chance: 0.05,
                crit_damage: 1.3,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::VestigialOrgan => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 128352.0,
                fire_rate: 199.0,
                magazine_capacity: 4.0,
                reload_time: 4.20,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::LightspeedBarrel => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 97169.0,
                fire_rate: 66.0,
                magazine_capacity: 9.0,
                reload_time: 2.80,
                crit_chance: 0.35,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::GuardianR4 => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 179145.0,
                fire_rate: 49.0,
                magazine_capacity: 1.0,
                reload_time: 1.47,
                crit_chance: 0.50,
                crit_damage: 2.0,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::DeathRoar => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 124965.0,
                fire_rate: 60.0,
                magazine_capacity: 7.0,
                reload_time: 2.80,
                crit_chance: 0.35,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::RestoredRelic => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 109813.0,
                fire_rate: 60.0,
                magazine_capacity: 12.0,
                reload_time: 2.50,
                crit_chance: 0.20,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::SigvoresProof => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 87476.0,
                fire_rate: 80.0,
                magazine_capacity: 10.0,
                reload_time: 2.80,
                crit_chance: 0.35,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::Subconsciousness => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 17063.0,
                fire_rate: 120.0,
                magazine_capacity: 10.0,
                reload_time: 1.45,
                crit_chance: 0.02,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 8.0,
            },
            Weapon::InABlink => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 20475.0,
                fire_rate: 75.0,
                magazine_capacity: 8.0,
                reload_time: 1.54,
                crit_chance: 0.02,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 10.0,
            },
            Weapon::Gangster => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 19888.0,
                fire_rate: 55.0,
                magazine_capacity: 9.0,
                reload_time: 1.68,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 12.0,
            },
            Weapon::Executor => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 7722.0,
                fire_rate: 109.0,
                magazine_capacity: 8.0,
                reload_time: 1.85,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 15.0,
            },
            Weapon::Smithereens => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 8989.0,
                fire_rate: 150.0,
                magazine_capacity: 7.0,
                reload_time: 1.6,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 10.0,
            },
            Weapon::TheLastKnight => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 10320.0,
                fire_rate: 120.0,
                magazine_capacity: 10.0,
                reload_time: 1.89,
                crit_chance: 0.03,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 9.0,
            },
            Weapon::Fireworks => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 22570.0,
                fire_rate: 67.0,
                magazine_capacity: 12.0,
                reload_time: 1.61,
                crit_chance: 0.01,
                crit_damage: 1.15,
                weak_point_damage: 1.0,
                bullets_per_shot: 6.0,
            },
            Weapon::RecipientUnknown => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 132590.0,
                fire_rate: 72.0,
                magazine_capacity: 6.0,
                reload_time: 2.1,
                crit_chance: 0.45,
                crit_damage: 1.8,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::Belief => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 92167.0,
                fire_rate: 80.0,
                magazine_capacity: 9.0,
                reload_time: 2.31,
                crit_chance: 0.45,
                crit_damage: 1.8,
                weak_point_damage: 1.7,
                bullets_per_shot: 1.0,
            },
            Weapon::DifferentDream => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 110259.0,
                fire_rate: 63.0,
                magazine_capacity: 12.0,
                reload_time: 2.15,
                crit_chance: 0.55,
                crit_damage: 1.8,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::SupermoonZ15 => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 101392.0,
                fire_rate: 65.0,
                magazine_capacity: 9.0,
                reload_time: 2.24,
                crit_chance: 0.50,
                crit_damage: 2.0,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::ForrestGaze => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 133703.0,
                fire_rate: 50.0,
                magazine_capacity: 7.0,
                reload_time: 2.52,
                crit_chance: 0.55,
                crit_damage: 2.0,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::WaveOfLight => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::ScoutRifle,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 36141.0,
                fire_rate: 250.0,
                magazine_capacity: 12.0,
                reload_time: 2.2,
                crit_chance: 0.10,
                crit_damage: 1.8,
                weak_point_damage: 1.8,
                bullets_per_shot: 1.0,
            },
            Weapon::TheAgeOfInnovation => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::ScoutRifle,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 33102.0,
                fire_rate: 250.0,
                magazine_capacity: 15.0,
                reload_time: 2.1,
                crit_chance: 0.07,
                crit_damage: 1.5,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::SillyWeeper => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::ScoutRifle,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 83359.0,
                fire_rate: 78.0,
                magazine_capacity: 8.0,
                reload_time: 2.1,
                crit_chance: 0.20,
                crit_damage: 1.5,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::NightmareHound => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::ScoutRifle,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 39963.0,
                fire_rate: 180.0,
                magazine_capacity: 18.0,
                reload_time: 2.24,
                crit_chance: 0.05,
                crit_damage: 1.2,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::HerosScar => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::ScoutRifle,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 29225.0,
                fire_rate: 240.0,
                magazine_capacity: 20.0,
                reload_time: 2.1,
                crit_chance: 0.10,
                crit_damage: 1.5,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::SonicCoOp => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::ScoutRifle,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 21431.0,
                fire_rate: 300.0,
                magazine_capacity: 25.0,
                reload_time: 2.0,
                crit_chance: 0.20,
                crit_damage: 1.5,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::BlueBeetle => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::ScoutRifle,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 29468.0,
                fire_rate: 200.0,
                magazine_capacity: 16.0,
                reload_time: 2.0,
                crit_chance: 0.25,
                crit_damage: 1.8,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::CaligosHorn => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 13409.0,
                fire_rate: 631.0,
                magazine_capacity: 30.0,
                reload_time: 1.68,
                crit_chance: 0.09,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::DivinePunishment => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 10624.0,
                fire_rate: 705.0,
                magazine_capacity: 35.0,
                reload_time: 1.55,
                crit_chance: 0.10,
                crit_damage: 1.7,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::MagnusAA => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 13190.0,
                fire_rate: 571.0,
                magazine_capacity: 30.0,
                reload_time: 1.68,
                crit_chance: 0.09,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::OminousHound => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 13930.0,
                fire_rate: 600.0,
                magazine_capacity: 31.0,
                reload_time: 1.75,
                crit_chance: 0.05,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::PhantomPain => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 10897.0,
                fire_rate: 722.0,
                magazine_capacity: 33.0,
                reload_time: 1.61,
                crit_chance: 0.09,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::MillenniumFrost => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Handgun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11329.0,
                fire_rate: 600.0,
                magazine_capacity: 15.0,
                reload_time: 1.26,
                crit_chance: 0.01,
                crit_damage: 1.8,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::HungryHound => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Handgun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 12712.0,
                fire_rate: 451.0,
                magazine_capacity: 15.0,
                reload_time: 1.19,
                crit_chance: 0.10,
                crit_damage: 1.7,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::NewBeginning => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Handgun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 9063.0,
                fire_rate: 750.0,
                magazine_capacity: 15.0,
                reload_time: 1.15,
                crit_chance: 0.10,
                crit_damage: 1.8,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::RedWolf => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Handgun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11165.0,
                fire_rate: 545.0,
                magazine_capacity: 12.0,
                reload_time: 1.05,
                crit_chance: 0.12,
                crit_damage: 1.8,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::TheLastDagger => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Handgun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 10926.0,
                fire_rate: 600.0,
                magazine_capacity: 12.0,
                reload_time: 1.2,
                crit_chance: 0.12,
                crit_damage: 2.0,
                weak_point_damage: 1.6,
                bullets_per_shot: 1.0,
            },
            Weapon::RoseOfAisha => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Handgun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 9042.0,
                fire_rate: 666.0,
                magazine_capacity: 14.0,
                reload_time: 1.12,
                crit_chance: 0.20,
                crit_damage: 1.8,
                weak_point_damage: 1.7,
                bullets_per_shot: 1.0,
            },
            Weapon::TheFinalMaster => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Handgun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 8861.0,
                fire_rate: 500.0,
                magazine_capacity: 20.0,
                reload_time: 1.1,
                crit_chance: 0.20,
                crit_damage: 2.0,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::TamedBeast => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 72897.0,
                fire_rate: 80.0,
                magazine_capacity: 12.0,
                reload_time: 2.8,
                crit_chance: 0.35,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::AlbionCavalryGun => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 13469.0,
                fire_rate: 451.0,
                magazine_capacity: 75.0,
                reload_time: 2.5,
                crit_chance: 0.07,
                crit_damage: 1.25,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::Cygnus => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11934.0,
                fire_rate: 521.0,
                magazine_capacity: 107.0,
                reload_time: 2.59,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::LionOfBlueMane => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 17289.0,
                fire_rate: 428.0,
                magazine_capacity: 110.0,
                reload_time: 3.29,
                crit_chance: 0.10,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::RascalV51 => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 10145.0,
                fire_rate: 571.0,
                magazine_capacity: 105.0,
                reload_time: 2.45,
                crit_chance: 0.04,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::UnfinishedStudy => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11736.0,
                fire_rate: 545.0,
                magazine_capacity: 125.0,
                reload_time: 3.01,
                crit_chance: 0.03,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::Albinism => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11568.0,
                fire_rate: 750.0,
                magazine_capacity: 26.0,
                reload_time: 1.46,
                crit_chance: 0.15,
                crit_damage: 1.3,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::AlterEgo => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 9908.0,
                fire_rate: 800.0,
                magazine_capacity: 35.0,
                reload_time: 1.74,
                crit_chance: 0.08,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::BlueBloodBloomer => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 8978.0,
                fire_rate: 1000.0,
                magazine_capacity: 27.0,
                reload_time: 1.32,
                crit_chance: 0.12,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::DevilsCall => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11086.0,
                fire_rate: 779.0,
                magazine_capacity: 26.0,
                reload_time: 1.32,
                crit_chance: 0.07,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::Firefly => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 9237.0,
                fire_rate: 857.0,
                magazine_capacity: 35.0,
                reload_time: 1.35,
                crit_chance: 0.20,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::RedEye => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 12712.0,
                fire_rate: 514.0,
                magazine_capacity: 48.0,
                reload_time: 1.89,
                crit_chance: 0.30,
                crit_damage: 1.3,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
        }
    }
}