use serde::{Deserialize, Serialize};
use std::fmt;

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Roll {
    pub roll_type: RollType,
    pub value: f64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum RollType {
    Atk, ElementAtk, WeakPointDamage, Crit, CritDamage, RoundsPerMagazine, ColossusDamage,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Module {
    pub name: String,
    pub module_type: ModuleType,
    pub effects: Vec<ModuleEffect>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModuleBonusType {
    Atk, WeakPointDamage, Crit, CritDamage, RoundsPerMagazine, ReloadTime, FireRate,
    EleEnhancement, EleMult, FiringFiesta, ShellCapacity
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ModuleEffect {
    pub effect_type: ModuleBonusType,
    pub value: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModuleType {
    None,
    Atk,
    SpecialMod,
    FireRate,
    EleEnhancement,
    WeakPointStrike,
    Crit,
    CritDamage,
    RoundsPerMagazine,
    ReloadTime,
    Recoil,
    Accuracy,
    Gunbarrel,
    FiringFiesta,
}

impl From<usize> for ModuleType {
    fn from(value: usize) -> Self {
        // Implement the conversion from usize to ModuleType
        // You may need to adjust this based on your exact ModuleType enum
        match value {
            0 => ModuleType::None,
            1 => ModuleType::Atk,
            2 => ModuleType::SpecialMod,
            3 => ModuleType::FireRate,
            4 => ModuleType::EleEnhancement,
            5 => ModuleType::WeakPointStrike,
            6 => ModuleType::Crit,
            7 => ModuleType::CritDamage,
            8 => ModuleType::RoundsPerMagazine,
            9 => ModuleType::ReloadTime,
            10 => ModuleType::Recoil,
            11 => ModuleType::Accuracy,
            12 => ModuleType::Gunbarrel,
            13 => ModuleType::FiringFiesta,
            _ => panic!("Invalid ModuleType value"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WeaponType {
    Handgun, HandCannon, Shotgun, SubmachineGun, MachineGun, AssaultRifle,
    TacticalRifle, ScoutRifle, SniperRifle, Launcher, BeamRifle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BulletType {
    GeneralRounds,
    SpecialRounds,
    ImpactRounds,
    HighPowerRounds
}

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum Weapon {
    AfterglowSword,
    AssassinsEdge,
    BurningHound,
    DeathRoar,
    Detachment,
    EnduringLegacy,
    EternalWillpower,
    ExplorersPath,
    FallenHope,
    GregsReversedFate,
    GuardianR4,
    ImmediateExecution,
    LightspeedBarrel,
    NazeistrasDevotion,
    Perferator,
    PiercingLight,
    Python,
    RestoredRelic,
    SecretGarden ,
    SigvoresProof,
    Tamer,
    TheUnwelcomed,
    Thundercage,
    VestigialOrgan,
    Viper,
    YoungNoblesAmbition,
    Subconsciousness,
    InABlink,
    Gangster,
    Executor,
    Smithereens,
    TheLastKnight,
    Fireworks,
}

impl Weapon {
    pub fn all() -> &'static [Weapon] {
        &[
            Weapon::AfterglowSword,
            Weapon::AssassinsEdge,
            Weapon::BurningHound,
            Weapon::DeathRoar,
            Weapon::Detachment,
            Weapon::EnduringLegacy,
            Weapon::EternalWillpower,
            Weapon::ExplorersPath,
            Weapon::FallenHope,
            Weapon::GregsReversedFate,
            Weapon::GuardianR4,
            Weapon::ImmediateExecution,
            Weapon::LightspeedBarrel,
            Weapon::NazeistrasDevotion,
            Weapon::Perferator,
            Weapon::PiercingLight,
            Weapon::Python,
            Weapon::RestoredRelic,
            Weapon::SecretGarden ,
            Weapon::SigvoresProof,
            Weapon::Tamer,
            Weapon::TheUnwelcomed,
            Weapon::Thundercage,
            Weapon::VestigialOrgan,
            Weapon::Viper,
            Weapon::YoungNoblesAmbition,
            Weapon::Subconsciousness,
            Weapon::InABlink,
            Weapon::Gangster,
            Weapon::Executor,
            Weapon::Smithereens,
            Weapon::TheLastKnight,
            Weapon::Fireworks,
        ]
    }
}

impl fmt::Display for Weapon {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct WeaponBaseStats {
    pub ele_enhancement: f64,
    pub flat_ele_atk: f64,
    pub colossus_atk: f64,
    pub ele_multiplier: f64,
    pub firing_fiesta: f64,
    pub weapon_type: WeaponType,
    pub bullet_type: BulletType,
    pub base_atk: f64,
    pub fire_rate: f64,
    pub magazine_capacity: f64,
    pub reload_time: f64,
    pub crit_chance: f64,
    pub crit_damage: f64,
    pub weak_point_damage: f64,
    pub bullets_per_shot: f64,
}

impl WeaponBaseStats {
    pub fn get(name: Weapon) -> Self {
        match name {
            Weapon::Thundercage => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 11055.0,
                fire_rate: 666.0,
                magazine_capacity: 26.0,
                reload_time: 1.4,
                crit_chance: 0.20,
                crit_damage: 2.0,
                weak_point_damage: 1.2,
                bullets_per_shot: 1.0,
            },
            Weapon::FallenHope => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 12813.0,
                fire_rate: 600.0,
                magazine_capacity: 35.0,
                reload_time: 1.7,
                crit_chance: 0.12,
                crit_damage: 1.7,
                weak_point_damage: 1.2,
                bullets_per_shot: 1.0,
            },
            Weapon::Perferator => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 67092.0,
                fire_rate: 100.0,
                magazine_capacity: 6.0,
                reload_time: 1.6,
                crit_chance: 0.20,
                crit_damage: 2.0,
                weak_point_damage: 2.25,
                bullets_per_shot: 1.0,
            },
            Weapon::AssassinsEdge => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 40788.0,
                fire_rate: 120.0,
                magazine_capacity: 9.0,
                reload_time: 1.4,
                crit_chance: 0.40,
                crit_damage: 2.0,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::ImmediateExecution => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 36920.0,
                fire_rate: 171.0,
                magazine_capacity: 12.0,
                reload_time: 1.7,
                crit_chance: 0.32,
                crit_damage: 1.5,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::ExplorersPath => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 55281.0,
                fire_rate: 109.0,
                magazine_capacity: 9.0,
                reload_time: 1.4,
                crit_chance: 0.27,
                crit_damage: 1.3,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::NazeistrasDevotion => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 38461.0,
                fire_rate: 150.0,
                magazine_capacity: 8.0,
                reload_time: 1.5,
                crit_chance: 0.45,
                crit_damage: 2.25,
                weak_point_damage: 1.7,
                bullets_per_shot: 1.0,
            },
            Weapon::BurningHound => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::HandCannon,
                bullet_type: BulletType::ImpactRounds,
                base_atk: 41726.0,
                fire_rate: 139.0,
                magazine_capacity: 12.0,
                reload_time: 1.75,
                crit_chance: 0.32,
                crit_damage: 1.5,
                weak_point_damage: 1.7,
                bullets_per_shot: 1.0,
            },
            Weapon::Tamer => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::MachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 17631.0,
                fire_rate: 625.0,
                magazine_capacity: 100.0,
                reload_time: 2.6,
                crit_chance: 0.10,
                crit_damage: 1.6,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::EternalWillpower => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::AssaultRifle,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 21370.0,
                fire_rate: 500.0,
                magazine_capacity: 25.0,
                reload_time: 1.9,
                crit_chance: 0.20,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::PiercingLight => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 193437.0,
                fire_rate: 48.0,
                magazine_capacity: 6.0,
                reload_time: 2.6,
                crit_chance: 0.40,
                crit_damage: 1.2,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::AfterglowSword => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SniperRifle,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 114206.0,
                fire_rate: 66.0,
                magazine_capacity: 6.0,
                reload_time: 2.5,
                crit_chance: 0.50,
                crit_damage: 2.0,
                weak_point_damage: 1.8,
                bullets_per_shot: 1.0,
            },
            Weapon::Viper => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 10359.0,
                fire_rate: 512.0,
                magazine_capacity: 50.0,
                reload_time: 1.75,
                crit_chance: 0.30,
                crit_damage: 1.85,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::YoungNoblesAmbition => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 13141.0,
                fire_rate: 455.0,
                magazine_capacity: 51.0,
                reload_time: 1.68,
                crit_chance: 0.35,
                crit_damage: 1.3,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::SecretGarden => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 10534.0,
                fire_rate: 480.0,
                magazine_capacity: 48.0,
                reload_time: 1.60,
                crit_chance: 0.50,
                crit_damage: 2.25,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::Detachment => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 17102.0,
                fire_rate: 360.0,
                magazine_capacity: 42.0,
                reload_time: 1.55,
                crit_chance: 0.30,
                crit_damage: 1.2,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::TheUnwelcomed => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 18108.0,
                fire_rate: 299.0,
                magazine_capacity: 36.0,
                reload_time: 1.54,
                crit_chance: 0.40,
                crit_damage: 1.5,
                weak_point_damage: 1.5,
                bullets_per_shot: 1.0,
            },
            Weapon::EnduringLegacy => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 13155.0,
                fire_rate: 571.0,
                magazine_capacity: 115.0,
                reload_time: 2.70,
                crit_chance: 0.20,
                crit_damage: 2.3,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::GregsReversedFate => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::TacticalRifle,
                bullet_type: BulletType::SpecialRounds,
                base_atk: 15614.0,
                fire_rate: 342.0,
                magazine_capacity: 30.0,
                reload_time: 1.4,
                crit_chance: 0.20,
                crit_damage: 2.0,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::Python => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::SubmachineGun,
                bullet_type: BulletType::GeneralRounds,
                base_atk: 9842.0,
                fire_rate: 923.0,
                magazine_capacity: 30.0,
                reload_time: 1.50,
                crit_chance: 0.05,
                crit_damage: 1.3,
                weak_point_damage: 2.0,
                bullets_per_shot: 1.0,
            },
            Weapon::VestigialOrgan => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 128352.0,
                fire_rate: 199.0,
                magazine_capacity: 4.0,
                reload_time: 4.20,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::LightspeedBarrel => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 97169.0,
                fire_rate: 66.0,
                magazine_capacity: 9.0,
                reload_time: 2.80,
                crit_chance: 0.35,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::GuardianR4 => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 179145.0,
                fire_rate: 49.0,
                magazine_capacity: 1.0,
                reload_time: 1.47,
                crit_chance: 0.50,
                crit_damage: 2.0,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::DeathRoar => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 124965.0,
                fire_rate: 60.0,
                magazine_capacity: 7.0,
                reload_time: 2.80,
                crit_chance: 0.35,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::RestoredRelic => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 109813.0,
                fire_rate: 60.0,
                magazine_capacity: 12.0,
                reload_time: 2.50,
                crit_chance: 0.20,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::SigvoresProof => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Launcher,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 87476.0,
                fire_rate: 80.0,
                magazine_capacity: 10.0,
                reload_time: 2.80,
                crit_chance: 0.35,
                crit_damage: 1.5,
                weak_point_damage: 1.0,
                bullets_per_shot: 1.0,
            },
            Weapon::Subconsciousness => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 17063.0,
                fire_rate: 120.0,
                magazine_capacity: 10.0,
                reload_time: 1.45,
                crit_chance: 0.02,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 8.0,
            },
            Weapon::InABlink => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 20475.0,
                fire_rate: 75.0,
                magazine_capacity: 8.0,
                reload_time: 1.54,
                crit_chance: 0.02,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 10.0,
            },
            Weapon::Gangster => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 19888.0,
                fire_rate: 55.0,
                magazine_capacity: 9.0,
                reload_time: 1.68,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 12.0,
            },
            Weapon::Executor => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 7722.0,
                fire_rate: 109.0,
                magazine_capacity: 8.0,
                reload_time: 1.85,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 15.0,
            },
            Weapon::Smithereens => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 8989.0,
                fire_rate: 150.0,
                magazine_capacity: 7.0,
                reload_time: 1.6,
                crit_chance: 0.01,
                crit_damage: 1.1,
                weak_point_damage: 1.0,
                bullets_per_shot: 10.0,
            },
            Weapon::TheLastKnight => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 10320.0,
                fire_rate: 120.0,
                magazine_capacity: 10.0,
                reload_time: 1.89,
                crit_chance: 0.03,
                crit_damage: 1.2,
                weak_point_damage: 1.0,
                bullets_per_shot: 9.0,
            },
            Weapon::Fireworks => Self {
                ele_enhancement: 0.0,
                flat_ele_atk: 0.0,
                colossus_atk: 0.0,
                ele_multiplier: 1.0,
                firing_fiesta: 0.0,
                weapon_type: WeaponType::Shotgun,
                bullet_type: BulletType::HighPowerRounds,
                base_atk: 22570.0,
                fire_rate: 67.0,
                magazine_capacity: 12.0,
                reload_time: 1.61,
                crit_chance: 0.01,
                crit_damage: 1.15,
                weak_point_damage: 1.0,
                bullets_per_shot: 6.0,
            },
        }
    }
}